name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  should_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up docker and login to GHCR
        uses: ./.github/actions/docker-setup-and-login
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          # GitHub only offers AMD64 codespaces, so there's no point in creating
          # multiplatform images.
          platforms: linux/amd64
          pull: true
