name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  DOCKER_BUILDKIT: "1"

jobs:
  should_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build image
        run: |
          docker version
          docker image build --pull --platform=linux/amd64 --tag=ghcr.io/$GITHUB_REPOSITORY:latest - < Dockerfile
